<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Manasa" failures="1" tests="5" name="testRunners.TestRunner" time="9.272" errors="0" timestamp="2025-07-24T21:00:51 CEST" skipped="0">
  <testcase classname="testRunners.TestRunner" name="runScenario" time="1.371"/>
  <testcase classname="testRunners.TestRunner" name="runScenario" time="2.150">
    <failure message="Navigated to checkout without adding any items expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Navigated to checkout without adding any items expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.EndToEndSteps.userDoNotAddProductToCartAndPlaceOrder(EndToEndSteps.java:28)
at âœ½.User do not add product to cart and place order(file:///E:/Manasa/Interview/Selenium_Java_Automation/Exact_Automation_Assesment/src/test/resources/features/Testing.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunners.TestRunner" name="runScenario" time="1.529"/>
  <testcase classname="testRunners.TestRunner" name="runScenario" time="2.679"/>
  <testcase classname="testRunners.TestRunner" name="runScenario" time="1.543"/>
</testsuite> <!-- testRunners.TestRunner -->
